FROM docker.pkg.github.com/k0inoue/github-packages-sample/gpack-sample:latest

RUN sudo apt-get update -q && sudo apt install -y --no-install-recommends \
    vim \
    && rm -rf /var/lib/apt/lists/*

