name: Docker Base Image Build & Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths:
      - 'docker/base/**'
      - '.github/workflows/base-publish.yml'

  # Run tests for any PRs.
  pull_request:
    paths:
      - 'docker/base/**'
      - '.github/workflows/base-publish.yml'


env:
  DOCKER_BUILDKIT: 1
  BASE_IMAGE_NAME: gpack-base
  BASE_DOCKER_FILE: docker/base/Dockerfile

jobs:
  # Build & Run tests.
  base-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Base Image Build and Tests
        run: |
            # build base image
            docker build . --file $BASE_DOCKER_FILE --tag $BASE_IMAGE_NAME

            # test base image
            docker run $BASE_IMAGE_NAME echo "TEST ECHO: test base docker image"

  # Push base image to GitHub Packages.
  base-push:
    # Ensure test job passes before pushing image.
    needs: base-build-test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/base/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.BASE_IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.BASE_IMAGE_NAME }}:0.0.1
