name: Publish Docker image
on:
  release:
    types: [ published ]
    branches: [ github-actions対応 ]
jobs:
  base_push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./docker/base/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: k0inoue/github-packages-sample/gpack-base
          tag_with_ref: true
